"""Static question bank for B1/B2 visa interview simulation.

Questions are phrased exactly as a real US consular officer would ask them —
short, direct, sometimes brusque. Based on real interview transcripts and
consular officer training materials.
"""

QUESTIONS = {
    "purpose": [
        {"id": "p1", "text": "What's the purpose of your trip?"},
        {"id": "p2", "text": "Who are you going to see?"},
        {"id": "p3", "text": "How do you know this person?"},
        {"id": "p4", "text": "Where will you stay?"},
        {"id": "p5", "text": "What places do you plan to visit?"},
        {"id": "p6", "text": "Do you have an itinerary?"},
        {"id": "p7", "text": "Is this personal or business?"},
        {"id": "p8", "text": "Have you been to the US before?"},
        {"id": "p9", "text": "Why the US? Why not somewhere closer?"},
        {"id": "p10", "text": "How long have you been planning this trip?"},
        {"id": "p11", "text": "Why are you going now? What's the occasion?"},
        {"id": "p12", "text": "Who's traveling with you?"},
        {"id": "p13", "text": "What will you do there for that many days?"},
        {"id": "p14", "text": "Have you booked your hotels?"},
    ],
    "return_intent": [
        {"id": "r1", "text": "How long do you plan to stay?"},
        {"id": "r2", "text": "When are you coming back?"},
        {"id": "r3", "text": "What's waiting for you back home?"},
        {"id": "r4", "text": "Do you have a return ticket?"},
        {"id": "r5", "text": "What happens when you get back? Back to work?"},
        {"id": "r6", "text": "Any commitments here during your trip — work, family?"},
        {"id": "r7", "text": "Has anyone in your family overstayed a US visa?"},
        {"id": "r8", "text": "Are you visiting any other countries on this trip?"},
        {"id": "r9", "text": "That's a long time. Why so many weeks?"},
        {"id": "r10", "text": "Do you plan to extend your stay once you're there?"},
        {"id": "r11", "text": "What ties do you have to your home country?"},
        {"id": "r12", "text": "Do you own property? A house, land?"},
    ],
    "employment": [
        {"id": "e1", "text": "What do you do?"},
        {"id": "e2", "text": "Where do you work?"},
        {"id": "e3", "text": "How long have you been there?"},
        {"id": "e4", "text": "Does your employer know about this trip?"},
        {"id": "e5", "text": "Have you taken leave for this?"},
        {"id": "e6", "text": "What's your position?"},
        {"id": "e7", "text": "Who handles your work while you're gone?"},
        {"id": "e8", "text": "You're self-employed? Tell me about your business."},
        {"id": "e9", "text": "What's your monthly income?"},
        {"id": "e10", "text": "Do you own property back home?"},
        {"id": "e11", "text": "Are you married? Kids?"},
        {"id": "e12", "text": "Where does your family live?"},
        {"id": "e13", "text": "What's your educational background?"},
        {"id": "e14", "text": "How many employees do you have?"},
    ],
    "financial": [
        {"id": "f1", "text": "Who's paying for this trip?"},
        {"id": "f2", "text": "How much do you expect to spend?"},
        {"id": "f3", "text": "How much money do you have in your bank account right now?"},
        {"id": "f4", "text": "Can you show me proof of funds?"},
        {"id": "f5", "text": "Someone's sponsoring you? Do you have a letter from them?"},
        {"id": "f6", "text": "How did you save for this trip?"},
        {"id": "f7", "text": "Do you have any outstanding loans?"},
        {"id": "f8", "text": "What's your annual salary?"},
        {"id": "f9", "text": "Who else is dependent on your income?"},
    ],
    "visa_history": [
        {"id": "v1", "text": "Have you applied for a US visa before?"},
        {"id": "v2", "text": "You were refused before. Tell me what happened."},
        {"id": "v3", "text": "Have you applied for visas to other countries?"},
        {"id": "v4", "text": "What countries have you traveled to?"},
        {"id": "v5", "text": "Have you ever overstayed a visa anywhere?"},
        {"id": "v6", "text": "Do you have a valid visa for any other country right now?"},
        {"id": "v7", "text": "What's changed since your last refusal?"},
    ],
    "us_contacts": [
        {"id": "u1", "text": "Do you have relatives in the US?"},
        {"id": "u2", "text": "What's your relationship to your host?"},
        {"id": "u3", "text": "What does your host do there?"},
        {"id": "u4", "text": "What's their immigration status?"},
        {"id": "u5", "text": "Has your host ever come to visit you here?"},
        {"id": "u6", "text": "Are you staying with them the entire time?"},
        {"id": "u7", "text": "Have you ever applied for immigration to the US?"},
        {"id": "u8", "text": "Is your relative petitioning for you?"},
    ],
    "business": [
        {"id": "b1", "text": "What's the name of your company?"},
        {"id": "b2", "text": "Who are you meeting in the US?"},
        {"id": "b3", "text": "What's the conference? Where is it?"},
        {"id": "b4", "text": "Will you receive any payment from a US company?"},
        {"id": "b5", "text": "What's the nature of this business?"},
        {"id": "b6", "text": "Does the US company know you're coming?"},
        {"id": "b7", "text": "Do you have an invitation letter?"},
    ],
    "challenge": [
        {"id": "c1", "text": "Why should I believe you'll come back?"},
        {"id": "c2", "text": "What makes you different from someone who would stay illegally?"},
        {"id": "c3", "text": "If you go and have a great time — why would you come back?"},
        {"id": "c4", "text": "A lot of people from your country overstay. Why are you different?"},
        {"id": "c5", "text": "Your friend is there — why hasn't your friend visited you instead?"},
        {"id": "c6", "text": "You're young and unmarried. What's keeping you from staying?"},
        {"id": "c7", "text": "I'm not convinced. Give me one strong reason."},
    ],
    "group": [
        {"id": "g1", "text": "Are you all traveling together?"},
        {"id": "g2", "text": "How do you all know each other?"},
        {"id": "g3", "text": "Who planned this trip?"},
        {"id": "g4", "text": "Who's paying for everyone?"},
        {"id": "g5", "text": "Have you all traveled together before?"},
        {"id": "g6", "text": "And you — what do you do for work?"},
        {"id": "g7", "text": "Are all of you returning at the same time?"},
        {"id": "g8", "text": "What if I approve some of you but not all?"},
    ],
}
