"""Static question bank for B1/B2 visa interview simulation."""

QUESTIONS = {
    "purpose": [
        {"id": "p1", "text": "What is the purpose of your visit to the United States?"},
        {"id": "p2", "text": "Who are you visiting?"},
        {"id": "p3", "text": "How do you know this person?"},
        {"id": "p4", "text": "Where exactly will you be staying in the US?"},
        {"id": "p5", "text": "What places do you plan to visit?"},
        {"id": "p6", "text": "Do you have a specific itinerary?"},
        {"id": "p7", "text": "Is this a personal trip or are you traveling for work?"},
        {"id": "p8", "text": "Have you ever been to the US before?"},
        {"id": "p9", "text": "Why do you want to visit the US specifically, rather than other countries?"},
        {"id": "p10", "text": "How long have you been planning this trip?"},
        {"id": "p11", "text": "Why are you going at this particular time?"},
        {"id": "p12", "text": "Will anyone be traveling with you?"},
    ],
    "return_intent": [
        {"id": "r1", "text": "How long do you plan to stay?"},
        {"id": "r2", "text": "What is your return date?"},
        {"id": "r3", "text": "What is waiting for you back home that ensures you will return?"},
        {"id": "r4", "text": "Do you have a return ticket booked?"},
        {"id": "r5", "text": "What will you do when you get back?"},
        {"id": "r6", "text": "Do you have any commitments in your home country during the time of your visit?"},
        {"id": "r7", "text": "Has anyone in your family previously overstayed a US visa?"},
        {"id": "r8", "text": "Do you plan to travel to any other countries during or after this trip?"},
        {"id": "r9", "text": "Why only that many weeks? That seems like a long time."},
        {"id": "r10", "text": "Do you plan to extend your stay once you arrive?"},
    ],
    "employment": [
        {"id": "e1", "text": "What do you do for work?"},
        {"id": "e2", "text": "Where do you work?"},
        {"id": "e3", "text": "How long have you been at this job?"},
        {"id": "e4", "text": "Does your employer know you're taking this trip?"},
        {"id": "e5", "text": "Have you taken leave approval for this trip?"},
        {"id": "e6", "text": "What is your position at your company?"},
        {"id": "e7", "text": "Who will handle your work while you're away?"},
        {"id": "e8", "text": "Are you self-employed? Tell me about your business."},
        {"id": "e9", "text": "What is your monthly income?"},
        {"id": "e10", "text": "Do you own property in your home country?"},
        {"id": "e11", "text": "Are you married? Do you have children?"},
        {"id": "e12", "text": "Where does your family live?"},
    ],
    "financial": [
        {"id": "f1", "text": "Who is paying for this trip?"},
        {"id": "f2", "text": "How much do you expect to spend during your visit?"},
        {"id": "f3", "text": "How much money do you have in your bank account?"},
        {"id": "f4", "text": "Can you show proof of funds?"},
        {"id": "f5", "text": "Is someone sponsoring your visit? Do you have a sponsorship letter?"},
        {"id": "f6", "text": "How did you save for this trip?"},
        {"id": "f7", "text": "Do you have any outstanding loans?"},
        {"id": "f8", "text": "What is your annual salary?"},
    ],
    "visa_history": [
        {"id": "v1", "text": "Have you previously applied for a US visa?"},
        {"id": "v2", "text": "Were you ever refused a US visa? When and why?"},
        {"id": "v3", "text": "Have you applied for a visa to any other country?"},
        {"id": "v4", "text": "What countries have you traveled to previously?"},
        {"id": "v5", "text": "Have you ever overstayed a visa in any country?"},
        {"id": "v6", "text": "Do you have a valid visa for any other country currently?"},
    ],
    "us_contacts": [
        {"id": "u1", "text": "Do you have relatives in the United States?"},
        {"id": "u2", "text": "What is your relationship to your host?"},
        {"id": "u3", "text": "What does your host do in the United States?"},
        {"id": "u4", "text": "What is the immigration status of your relatives in the US?"},
        {"id": "u5", "text": "Has your US contact ever visited you in your home country?"},
        {"id": "u6", "text": "Are you planning to live with your relative during the entire visit?"},
    ],
    "business": [
        {"id": "b1", "text": "What company do you work for and what is your role?"},
        {"id": "b2", "text": "Who are you meeting with in the US?"},
        {"id": "b3", "text": "What is the name and location of the conference or meeting?"},
        {"id": "b4", "text": "Will you be receiving any payment from a US company during your visit?"},
        {"id": "b5", "text": "What is the nature of the business transaction?"},
        {"id": "b6", "text": "Does your US counterpart know you are coming?"},
    ],
    "challenge": [
        {"id": "c1", "text": "Why should I believe you will return home?"},
        {"id": "c2", "text": "What makes your situation different from someone who intends to stay illegally?"},
        {"id": "c3", "text": "If I approved your visa and you had a great time — why wouldn't you just stay?"},
        {"id": "c4", "text": "Many people from your country overstay their visas. How are you different?"},
        {"id": "c5", "text": "You said you're visiting a friend — why hasn't your friend visited you instead?"},
    ],
}
